---
apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: ambassador
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: petstore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore
  namespace: ambassador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
        - name: petstore-backend
          image: docker.io/swaggerapi/petstore3:unstable
          ports:
            - name: http
              containerPort: 8080